title: "Laksayo's portfolio and blog"
author: laksayo
email: laksayo.feedtheshark@gmail.com
description: "Showcase of art and blog"

# Header Links
homepage: https://laksayo.github.io
instagram_username: laksayo
github_username: laksayo

# Header Pages for Navigation
header_pages:
  - "/Info/"
  - "/Conventions/"
  - "/rambles/"

# Build settings
# Remove theme: or remote_theme: because the theme is local
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: specify where your layouts are if not default
# You can keep layouts in _layouts inside your theme folder
