title: "Laksayo's portfolio and blog"
author: laksayo
email: laksayo.feedtheshark@gmail.com
description: "Showcase of art and blog"

# Header Pages for Navigation
header_pages:
  - "/info/"
  - "/conventions/"
  - "/rambles/"

# Footer
footer:
  author: "Laksayo"
  message: "Illustration. Imagination. Connection. Always experimenting, always hands-on."
  copyright: "All rights reserved."
  social:
    - name: Telegram
      url: https://web.telegram.org/k/#@laksayostore
      icon: /assets/icons/telegram.png
    - name: Instagram
      url: https://instagram.com/laksayo
      icon: /assets/icons/instagram.png
    - name: Vgen
      url: https://vgen.co/laksayo
      icon: /assets/icons/vgen.png
    - name: Kofi
      url: https://kofi.com/laksayo
      icon: /assets/icons/kofi.png
      
# Build settings
# Remove theme: or remote_theme: because the theme is local
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: specify where your layouts are if not default
# You can keep layouts in _layouts inside your theme folder
